package com.thedavelopers.eventqr.tests.admin;

import com.thedavelopers.eventqr.base.BaseTest;
import com.thedavelopers.eventqr.config.TestConfig;
import com.thedavelopers.eventqr.pages.AdminDashboardPage;
import com.thedavelopers.eventqr.pages.LoginPage;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * TestFlow 7.4 — Admin Audit Logs (AAL-1..AAL-2).
 * activity_admin_audit_logs.xml: filter chips + list/empty + refresh.
 * Log content is data-dependent (generated by app activity), so assertions
 * branch on the empty state.
 */
public class AdminAuditLogsTest extends BaseTest {

    @BeforeEach
    void openAuditLogs() {
        LoginPage login = new LoginPage();
        login.login(TestConfig.ADMIN_EMAIL, TestConfig.ADMIN_PASS);
        new AdminDashboardPage().openLogsTab();
    }

    @Test
    @DisplayName("AAL-1: Audit logs screen renders with filter chips")
    void auditLogsScreenRenders() {
        assertAll(
                () -> assertTrue(isTextDisplayed("Audit Logs"), "Audit Logs title expected"),
                () -> assertTrue(isDisplayed(id("chipAuditAll")), "All chip expected"),
                () -> assertTrue(isDisplayed(id("chipAuditAccount")), "Account chip expected"),
                () -> assertTrue(isDisplayed(id("chipAuditApproval")), "Approval chip expected"),
                () -> assertTrue(isDisplayed(id("chipAuditNotification")), "Notification chip expected"),
                () -> assertTrue(isDisplayed(id("chipAuditSecurity")), "Security chip expected")
        );
    }

    @Test
    @DisplayName("AAL-2: Log entries or empty state render with refresh")
    void logsOrEmptyStateRender() {
        assertTrue(isDisplayed(id("recyclerAuditLogs"))
                        || isTextDisplayed("No audit logs yet."),
                "Log entries or the empty state expected (data-dependent)");
        swipeDown();
        assertTrue(isDisplayed(id("swipeRefreshAuditLogs"))
                        || isDisplayed(id("recyclerAuditLogs"))
                        || isTextDisplayed("No audit logs yet."),
                "Pull-to-refresh keeps the screen rendered");
    }
}