package com.thedavelopers.eventqr.features.organizer

object OrganizerMvpPlaceholders {
    const val TODO_BACKEND =
        "TODO: Replace organizer MVP sample data with organizer-scoped backend/API calls once contracts are finalized."

    val events = listOf(
        OrganizerMvpEvent(
            id = "evt-tech-2024",
            title = "Tech Conference 2024",
            organizerName = "Tech Society",
            dateTime = "May 25, 2024, 9:00 AM - 5:00 PM",
            shortDate = "May 25, 2024",
            venue = "Main Auditorium",
            status = "Approved",
            submittedDate = "May 1, 2024",
            adminRemarks = "Approved. Please coordinate with the venue team.",
            additionalOrganizers = listOf("helper1@university.edu", "helper2@university.edu"),
            registeredCount = 250L,
            enteredCount = 198L,
            attendedCount = 180L,
            exitedCount = 156L,
            noShowCount = 47L,
            totalTransactions = 1250L,
            successfulScans = 1186L,
            rejectedScans = 64L,
            benefitClaims = 98L,
            boothSessionVisits = 245L,
            rewardRedemptions = 45L,
            totalPointsAwarded = 8450L,
            idTemplateStatus = "Configured",
            rewardsStatus = "Enabled",
            staffCount = 5L,
            scanPurposesCount = 8L,
        ),
        OrganizerMvpEvent(
            id = "evt-bootcamp-2026",
            title = "Coding Bootcamp",
            organizerName = "Tech Society",
            dateTime = "June 15, 2026, 8:30 AM - 4:00 PM",
            shortDate = "June 15, 2026",
            venue = "Computer Laboratory 1",
            status = "Approved",
            submittedDate = "May 1, 2026",
            adminRemarks = "Approved. Please coordinate with the venue team.",
            additionalOrganizers = listOf("helper1@university.edu", "helper2@university.edu"),
            registeredCount = 4L,
            enteredCount = 3L,
            attendedCount = 3L,
            exitedCount = 1L,
            noShowCount = 1L,
            totalTransactions = 24L,
            successfulScans = 18L,
            rejectedScans = 6L,
            benefitClaims = 3L,
            boothSessionVisits = 8L,
            rewardRedemptions = 2L,
            totalPointsAwarded = 650L,
            idTemplateStatus = "Ready",
            rewardsStatus = "Enabled",
            staffCount = 3L,
            scanPurposesCount = 9L,
        ),
        OrganizerMvpEvent(
            id = "evt-sports-2026",
            title = "Sports Festival",
            organizerName = "Athletics Club",
            dateTime = "June 20, 2026, 7:00 AM - 5:00 PM",
            shortDate = "June 20, 2026",
            venue = "University Field",
            status = "Pending",
            submittedDate = "May 12, 2026",
            adminRemarks = "Pending admin review.",
            additionalOrganizers = listOf("sports.helper@university.edu"),
            registeredCount = 0L,
            enteredCount = 0L,
            attendedCount = 0L,
            exitedCount = 0L,
            noShowCount = 0L,
            totalTransactions = 0L,
            successfulScans = 0L,
            rejectedScans = 0L,
            benefitClaims = 0L,
            boothSessionVisits = 0L,
            rewardRedemptions = 0L,
            totalPointsAwarded = 0L,
            idTemplateStatus = "Not configured",
            rewardsStatus = "Not configured",
            staffCount = 0L,
            scanPurposesCount = 0L,
        ),
    )

    // TODO: Replace this in-memory cache with a real organizer event store/ViewModel when architecture is available.
    var cachedEvents: List<OrganizerMvpEvent> = emptyList()

    val attendees = listOf(
        OrganizerMvpAttendee(
            id = "att-001",
            eventId = "evt-tech-2024",
            name = "John Doe",
            email = "john.doe@example.com",
            phone = "+63 917 555 0101",
            registrationStatus = "Registered",
            currentEventStatus = "Checked In / Entered",
            points = 150,
            lastTransactionTime = "9:15 AM",
            registeredDate = "May 10, 2024",
            qrCredentialStatus = "Active",
            recentTransactions = listOf(
                OrganizerMvpTransactionEntry("Check-in logged"),
                OrganizerMvpTransactionEntry("Attendance scan approved"),
                OrganizerMvpTransactionEntry("Booth visit recorded"),
            ),
            recentRejectedScans = emptyList(),
        ),
        OrganizerMvpAttendee(
            id = "att-002",
            eventId = "evt-tech-2024",
            name = "Jane Smith",
            email = "jane.smith@example.com",
            phone = "+63 918 555 0140",
            registrationStatus = "Registered",
            currentEventStatus = "Checked In / Entered",
            points = 200,
            lastTransactionTime = "9:30 AM",
            registeredDate = "May 12, 2024",
            qrCredentialStatus = "Active",
            recentTransactions = listOf(
                OrganizerMvpTransactionEntry("Check-in logged"),
                OrganizerMvpTransactionEntry("Benefit claim approved"),
                OrganizerMvpTransactionEntry("Reward redemption approved"),
            ),
            recentRejectedScans = emptyList(),
        ),
        OrganizerMvpAttendee(
            id = "att-003",
            eventId = "evt-tech-2024",
            name = "Mike Johnson",
            email = "mike.j@example.com",
            phone = "+63 919 555 0188",
            registrationStatus = "Registered",
            currentEventStatus = "No-show",
            points = 0,
            lastTransactionTime = "No scans",
            registeredDate = "May 15, 2024",
            qrCredentialStatus = "Issued",
            recentTransactions = emptyList(),
            recentRejectedScans = listOf("Wrong event QR rejected"),
        ),
        OrganizerMvpAttendee(
            id = "att-004",
            eventId = "evt-tech-2024",
            name = "Sarah Williams",
            email = "sarah.w@example.com",
            phone = "+63 920 555 0133",
            registrationStatus = "Registered",
            currentEventStatus = "Attended",
            points = 100,
            lastTransactionTime = "10:05 AM",
            registeredDate = "May 16, 2024",
            qrCredentialStatus = "Active",
            recentTransactions = listOf(
                OrganizerMvpTransactionEntry("Session entry recorded"),
                OrganizerMvpTransactionEntry("Attendance recorded"),
            ),
            recentRejectedScans = emptyList(),
        ),
    )

    val transactions = listOf(
        OrganizerMvpTransaction(
            id = "TXN-2024-0001",
            eventId = "evt-tech-2024",
            eventTitle = "Tech Conference 2024",
            attendeeId = "att-001",
            attendeeName = "John Doe",
            qrId = "QR-2024-001",
            staffId = "staff-001",
            staffName = "Sarah Johnson",
            scanPurpose = "Check-In",
            type = "Entry",
            timestamp = "May 25, 2024 9:03 AM",
            status = "Successful",
            message = "Check-in logged",
            reason = "Entry accepted",
            deviceSource = "Gate Scanner A",
            pointsDelta = 20,
            relatedItem = "Main entrance",
        ),
        OrganizerMvpTransaction(
            id = "TXN-2024-0002",
            eventId = "evt-tech-2024",
            eventTitle = "Tech Conference 2024",
            attendeeId = "att-002",
            attendeeName = "Jane Smith",
            qrId = "QR-2024-002",
            staffId = "staff-002",
            staffName = "Mike Chen",
            scanPurpose = "Session Entry",
            type = "Attendance",
            timestamp = "May 25, 2024 10:15 AM",
            status = "Successful",
            message = "Session entry recorded",
            reason = "Attendance recorded",
            deviceSource = "Room 201 Scanner",
            pointsDelta = 30,
            relatedItem = "AI Workshop",
        ),
        OrganizerMvpTransaction(
            id = "TXN-2024-0003",
            eventId = "evt-tech-2024",
            eventTitle = "Tech Conference 2024",
            attendeeId = "att-003",
            attendeeName = "Kevin Reyes",
            qrId = "QR-2024-999",
            staffId = "staff-003",
            staffName = "Emily Davis",
            scanPurpose = "Check-In",
            type = "Entry",
            timestamp = "May 25, 2024 10:21 AM",
            status = "Rejected",
            message = "Wrong event QR",
            reason = "Wrong event QR",
            deviceSource = "Gate Scanner B",
            pointsDelta = 0,
            relatedItem = "Main entrance",
        ),
        OrganizerMvpTransaction(
            id = "TXN-2024-0004",
            eventId = "evt-tech-2024",
            eventTitle = "Tech Conference 2024",
            attendeeId = "att-004",
            attendeeName = "Sarah Williams",
            qrId = "QR-2024-004",
            staffId = "staff-002",
            staffName = "Mike Chen",
            scanPurpose = "Reward Redemption",
            type = "Reward Redemption",
            timestamp = "May 25, 2024 11:12 AM",
            status = "Successful",
            message = "Reward redemption recorded",
            reason = "Reward claimed",
            deviceSource = "Rewards Booth",
            pointsDelta = -50,
            relatedItem = "Event lanyard",
        ),
    )

    val staff = listOf(
        OrganizerMvpStaff(
            id = "staff-001",
            name = "Sarah Johnson",
            email = "sarah.j@example.com",
            assignedEventId = "evt-tech-2024",
            assignedEvent = "Tech Conference 2024",
            roleLabel = "Lead Scanner",
            accessStatus = "Active",
            addedDate = "May 15, 2024",
            permissions = listOf("Scan QR", "Reprint ID", "View attendee details", "Validate claims"),
        ),
        OrganizerMvpStaff(
            id = "staff-002",
            name = "Mike Chen",
            email = "mike.c@example.com",
            assignedEventId = "evt-tech-2024",
            assignedEvent = "Tech Conference 2024",
            roleLabel = "Scanner",
            accessStatus = "Active",
            addedDate = "May 16, 2024",
            permissions = listOf("Scan QR", "View attendee details"),
        ),
        OrganizerMvpStaff(
            id = "staff-003",
            name = "Emily Davis",
            email = "emily.d@example.com",
            assignedEventId = "evt-tech-2024",
            assignedEvent = "Tech Conference 2024",
            roleLabel = "Support Staff",
            accessStatus = "Active",
            addedDate = "May 18, 2024",
            permissions = listOf("Scan QR", "Reward redemption"),
        ),
    )

    val availableUsers = listOf(
        OrganizerMvpStaff(
            id = "user-100",
            name = "Alex Rivera",
            email = "alex.r@example.com",
            assignedEventId = "",
            assignedEvent = "Not assigned",
            roleLabel = "Scanner",
            accessStatus = "Available",
            addedDate = "Not added",
            permissions = listOf("Scan QR"),
        ),
        OrganizerMvpStaff(
            id = "user-101",
            name = "Dana Cruz",
            email = "dana.c@example.com",
            assignedEventId = "",
            assignedEvent = "Not assigned",
            roleLabel = "Support Staff",
            accessStatus = "Available",
            addedDate = "Not added",
            permissions = listOf("View attendee details"),
        ),
    )

    // TODO: Replace this in-memory demo state with backend staff assignment persistence.
    val editableStaff = staff.toMutableList()

    val scanPurposes = listOf(
        OrganizerMvpScanPurpose("ID Printing", "Print event ID badge for attendees", true, "Prevent duplicate ID print", true, false, 0, "Registration"),
        OrganizerMvpScanPurpose("ID Reprinting", "Reprint lost or damaged ID badges", true, "Allow staff-confirmed reprint", true, false, 0, "Registration"),
        OrganizerMvpScanPurpose("Entrance Logging", "Log attendee entry at event entrance", true, "Prevent duplicate entry", true, false, 0, "Gate"),
        OrganizerMvpScanPurpose("Attendance Recording", "Record attendance at sessions or activities", true, "Prevent duplicate attendance if configured", false, true, 20, "Session"),
        OrganizerMvpScanPurpose("Benefit Claiming", "Validate meals, kits, or other attendee benefits", true, "Prevent duplicate benefit claim", true, false, 0, "Benefit"),
        OrganizerMvpScanPurpose("Booth/Session Visit", "Track attendee visits per booth or session", true, "Allow one scan per selected booth/session", false, true, 10, "Booth or session"),
        OrganizerMvpScanPurpose("Reward Redemption", "Validate event reward claims", true, "Prevent duplicate reward claim", true, false, 0, "Reward"),
        OrganizerMvpScanPurpose("Exit Logging", "Log attendee exit from the event", true, "Allow latest exit update", true, false, 0, "Exit gate"),
    )

    // TODO: Replace this in-memory demo state with backend scan purpose rule persistence.
    val editableScanPurposes = scanPurposes.toMutableList()
}
