package com.thedavelopers.eventqr.features.organizer

data class OrganizerMvpEvent(
    val id: String,
    val title: String,
    val organizerName: String,
    val dateTime: String,
    val shortDate: String,
    val venue: String,
    val status: String,
    val submittedDate: String,
    val adminRemarks: String,
    val additionalOrganizers: List<String>,
    val registeredCount: Long,
    val enteredCount: Long,
    val attendedCount: Long,
    val exitedCount: Long,
    val noShowCount: Long,
    val totalTransactions: Long,
    val successfulScans: Long,
    val rejectedScans: Long,
    val benefitClaims: Long,
    val boothSessionVisits: Long,
    val rewardRedemptions: Long,
    val totalPointsAwarded: Long,
    val idTemplateStatus: String,
    val rewardsStatus: String,
    val staffCount: Long,
    val scanPurposesCount: Long,
    val description: String = "",
    val registrationCloseDate: String = "-",
    val capacity: Int = 0,
    val currentAttendeeCount: Int = 0,
    val availableSlots: Int = 0,
)
